### PR TITLE
#160814312 Setup for react project files

### PR DESCRIPTION
**Pull request by byarustev**
#### What does this PR do?
Setup react project files for authors haven frontend
#### Description of Task to be completed?
- Set up project files
- Set up the file structure 
#### How should this be manually tested?
- Clone the repository
- Use `npm install` to install dependencies
- Run `npm start` to run the project 
- Use the link that will be shown to access the project through the browser
#### What are the relevant pivotal tracker stories?
#160814312

### CODE REVIEW

**Comment by marthamareal** [comment]
Great job @byarustev, am suggesting you "Eject from create-react-app" such that we can have access to the settings. and also you can edit in the index.html title about the app.

**Comment by byarustev** [comment]
> Great job @byarustev, am suggesting you "Eject from create-react-app" such that we can have access to the settings. and also you can edit in the index.html title about the app.

done with the index.html suggestion, But could you help me understand what you are meaning by eject? I am not familiar with that.

You can eject by using a command `**npm run eject**`, and what it simply does is to reveal for you the default configurations done by the "**create-react app**" such that you can have full control over the project's settings.

**Comment by cmplx-xyttmt** [comment]
LGTM

**Review by ruganda — COMMENTED** [review]
Hey, @byarustev good work, but I think we might not need service workers for this project. I would suggest that you refactor and remove the service worker files and imports

**Comment by byarustev** [comment]
@ruganda 
I think their importance may come in handy when the time comes.

**Comment by ruganda** [comment]
LGTM

**Pull request merged**
