### PR TITLE
#160814740 users should have landing page

### PR DESCRIPTION
**Pull request by byarustev**
#### What does this PR do?
implements landing page for authors haven
#### Description of Task to be completed?
- adds landing page with slider showcasing what authors haven is about.
- previews some articles from authors a given user follows
- previews random articles if the user does not follow any user as yet

#### How should this be manually tested?
- start the app using `npm start` and navigate to home 
- a landing page should be shown with sample article

#### What are the relevant pivotal tracker stories?
[#160814740](https://www.pivotaltracker.com/story/show/160814740)
#### Screenshots (if appropriate)
screencapture-localhost-3000-2018-10-23-12_17_53

### CODE REVIEW

**Comment by cmplx-xyttmt** [comment]
Hey @byarustev, overall, good work.
However, when testing the app, I noticed an issue: When someone is logged in, and then clicks on the `GET STARTED` button, it takes them to the sign-up page. Ideally, this shouldn't happen.

There are 2 potential fixes you could consider for when a user is logged in:
- Hide the `GET STARTED` button.
- Redirect to the `write an article page` when they click on that button.

**Comment by byarustev** [comment]
> Hey @byarustev, overall, good work.
> However, when testing the app, I noticed an issue: When someone is logged in, and then clicks on the `GET STARTED` button, it takes them to the sign-up page. Ideally, this shouldn't happen.
> 
> There are 2 potential fixes you could consider for when a user is logged in:
> 
> * Hide the `GET STARTED` button.
> * Redirect to the `write an article page` when they click on that button.

Thanks Isaac for this feedback. I have worked on it. feel free to check it out. I decided to go with the second suggestion.

**Comment by marthamareal** [comment]
Great work @byarustev , maybe you can add the functionality of viewing an article when someone clicks on it from the stories list on the landing page.

Also you can give color black to words in this image
screen shot 2018-10-23 at 15 24 22

**Review by cmplx-xyttmt — COMMENTED** [review]
LGTM

**Comment by byarustev** [comment]
> Great work @byarustev , maybe you can add the functionality of viewing an article when someone clicks on it from the stories list on the landing page.
> 
> Also you can give color black to words in this image
> screen shot 2018-10-23 at 15 24 22

Thanks @ruganda . These two issues have been fixed.
screen shot 2018-10-24 at 09 34 19

**Review by ruganda — COMMENTED** [review]
LGTM

**Comment by marthamareal** [comment]
LGTM

**Pull request merged**
