### PR TITLE
#160814321 Implement password reset

### PR DESCRIPTION
**Pull request by ruganda**
#### What does this PR do?
- Implements password reset
#### Description of Task to be completed?
- enable users to request for a password reset
- enable users to reset their passwords via the email link
#### How should this be manually tested?
- navigate to `/reset_password` and provide an email whose password is to be reset.
- Check your email inbox for the next instructions
- Provide `the new password` in the password reset form. 

#### What are the relevant pivotal tracker stories?
[#160814321](https://www.pivotaltracker.com/story/show/160814321)
#### Screenshots (if appropriate)
NA

### CODE REVIEW

**Comment by marthamareal** [comment]
Weldone @ruganda, however, you can try to fix the codeclimate issues in order to keep quality in the project(best practices). For things that have duplicates refactor and form functions which can be called.

**Comment by cmplx-xyttmt** [comment]
Other than the message that says `Failed to login with that social media platform` when I haven't clicked anything, LGTM.

**Comment by byarustev** [comment]
LGTM

**Comment by marthamareal** [comment]
@ruganda, good work, however you can edit your PR message

**Pull request closed without merging**
