### PR TITLE
#160814320 Users should be able to signup

### PR DESCRIPTION
**Pull request by byarustev**
#### What does this PR do?
Implements signup using username, email and password
#### Description of Task to be completed?
- Create html signup form
- Front end form validation
- Submit the validated inputs to back end api
- Unit tests for the feature
- update materialise link to latest meterialize version
- Redirect on successfull registration
#### How should this be manually tested?
- Run `npm start` 
- Navigate to signup page by clicking on **register**. 
- Fill in the form and click submit. 
#### What are the relevant pivotal tracker stories?
[#160814320](https://www.pivotaltracker.com/story/show/160814320)
#### Screenshots 
screen shot 2018-10-11 at 12 27 29

screen shot 2018-10-09 at 12 32 52

### CODE REVIEW

**Comment by marthamareal** [comment]
Good work @byarustev ,
However the container is doing so much work compared to the component, am suggesting you move the div for the form and validation method to the component, then call that component in the container to display the form. This is because that signup container is expected to have another component (SocialButtons). you can refer to the login PR.

**Comment by cmplx-xyttmt** [comment]
Hey @byarustev, good work so far.
However, there is a small issue: When I enter a password, it is shown in clear text.  Is this how it's supposed to be?

**Comment by byarustev** [comment]
> Hey @byarustev, good work so far.
> However, there is a small issue: When I enter a password, it is shown in clear text. Is this how it's supposed to be?

thanks Isaac. issue sorted

**Comment by cmplx-xyttmt** [comment]
LGTM

**Comment by ruganda** [comment]
LGTM

**Pull request merged**
