### PR TITLE
#160814328 Enable Pagination support for articles

### PR DESCRIPTION
**Pull request by marthamareal**
#### What does this PR do?
enables users traverse through articles 

#### Description of Task to be completed?
- add pagination component
- write tests
#### How should this be manually tested?
- run the project with `npm start`
- navigate to Articles on the menu and paginate at the bottom of the window.
#### What are the relevant pivotal tracker stories?
[#160814328](https://www.pivotaltracker.com/story/show/160814328)
#### Screenshots
screen shot 2018-10-23 at 15 17 35
screen shot 2018-10-23 at 15 18 12
screen shot 2018-10-23 at 15 18 25

### CODE REVIEW

**Comment by cmplx-xyttmt** [comment]
good work @marthamareal. LGTM

**Comment by ruganda** [comment]
Good work @marthamareal ,  but how about adding an option for viewing the last page,  or the first page.

**Comment by byarustev** [comment]
Nice work Martha. However, in your PR description, you have a heading of screenshots but none was added. Please consider adding a screenshot or removing the heading.

**Comment by ruganda** [comment]
LGTM

**Comment by marthamareal** [comment]
> Nice work Martha. However, in your PR description, you have a heading of screenshots but none was added. Please consider adding a screenshot or removing the heading.

Thanks have worked on it

**Pull request merged**
