### PR TITLE
#161258025 Refactor code to follow Airbnb style guide

### PR DESCRIPTION
**Pull request by ruganda**
#### What does this PR do?
- Refactor the code base to follow Airbnb style guide
#### Description of Task to be completed?
-  Refactor the codebase to follow Airbnb style guide
- Refactor the codebase to follow es6
#### How should this be manually tested?
- setup Eslint for your project locally to follow Airbnb style guide, and you should not be able to get linting errors on this branch
#### What are the relevant pivotal tracker stories?
- [#161258025](https://www.pivotaltracker.com/story/show/161258025)
Note :
This  PR contains a commit from the `password-reset feature`.

### CODE REVIEW

**Comment by cmplx-xyttmt** [comment]
Aside from test coverage lowering, LGTM

**Comment by byarustev** [comment]
@ruganda thanks for the good work. However, I see this code contains new files for password reset. Don't you think this has to be included in the PR description?

**Comment by ruganda** [comment]
Thanks for pointing that out @byarustev, I had discussed that with the rest of the teammates. I'm sorry that I didn't update you on that. But I think  it is a good Idea to add it to the PR description

**Comment by marthamareal** [comment]
@ruganda, Is there a way of maintaining our coverage?
Also, am suggesting you add password rest to the PR description since its what we will consider

**Comment by ruganda** [comment]
@marthamareal, Thanks for pointing that out, but I think we might have to deal with the 0.2 drop since we didn't implement any feature in this PR, but `refactoring`. Refactoring is not meant to add any new functionality but, I can't account for the coverage drop.

**Pull request merged**
